usage: Apply this to any method that requires some conditions to be met for execution.
responses:
  403:
    description: Returned when action is not allowed, e.g. required conditions are not met.
    body:
      type: Error
