type: OAuth 2.0
describedBy:
  headers:
    Authorization:
      type: string
      example: Bearer iDbsaZHplNEL1thqvGsfYFyb_4P4Fv6uCCAGcENK_ho
settings:
  accessTokenUri: http://0.0.0.0:3000/oauth/token
  authorizationGrants: ["password"]
