require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0.3.1

Layout/ClassStructure:
  Enabled: true

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2]

Layout/LineLength:
  IgnoredPatterns: ['\A\s*#'] # Allow too long comment lines
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
  Max: 25

Metrics/BlockLength:
  ExcludedMethods: ['configure', 'included','task']
  Exclude:
    - config/routes.rb
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
  Max: 25

Rails/BulkChangeTable:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Max: 15

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/MixinUsage:
  Exclude:
    - bin/*

Style/Send:
  Enabled: true
