AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.5.1
  TargetRailsVersion: 5.2.0

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2]

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
  Max: 20

Metrics/BlockLength:
  ExcludedMethods: ['configure', 'included','task']
  Exclude:
    - config/routes.rb
    - spec/**/*

Metrics/LineLength:
  IgnoredPatterns: ['\A\s*#'] # Allow too long comment lines
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
  Max: 25

Style/AndOr:
  EnforcedStyle: conditionals

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false
