# TODO: Enable when https://github.com/toshimaru/rubocop-rails_config/issues/42 is fixed
#inherit_gem:
#  rubocop-rails_config:
#    - config/rails.yml

AllCops:
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - db/schema.rb
  TargetRubyVersion: 2.6.3
  TargetRailsVersion: 5.2.3

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2]

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/AbcSize:
  Exclude:
    - db/migrate/*
  Max: 25

Metrics/BlockLength:
  ExcludedMethods: ['configure', 'included','task']
  Exclude:
    - config/routes.rb
    - spec/**/*

Metrics/LineLength:
  IgnoredPatterns: ['\A\s*#'] # Allow too long comment lines
  Max: 120

Metrics/MethodLength:
  Exclude:
    - db/migrate/*
  Max: 25

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/*
