language: ruby
rvm: 2.6.3
cache: bundler
services:
  - postgresql
addons:
  postgresql: '11.3'
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec
