version: '3.3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournaments-api-development
    ports:
      - '5432:5432'

  docs:
    image: mattjtodd/raml2html:latest
    working_dir: /tournaments-api
    command: -i ./docs/index.raml -o ./public/docs.html
    volumes:
      - .:/tournaments-api

#  redis:
#    image: redis:latest
#    ports:
#      - '6379:6379'

  web:
    build: .
    working_dir: /tournaments-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache # without it spring cannot find gems
      WEB_CONCURRENCY: 1
    links:
      - db
#      - redis
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/tournaments-api
      - cache-volume:/bundle_cache

volumes:
  cache-volume:
