version: '3.3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: untitled-tournaments-development
    ports:
      - '5432:5432'

#  redis:
#    image: redis:latest
#    ports:
#      - '6379:6379'

  web:
    build: .
    working_dir: /untitled-tournaments
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
#      APIPIE_RECORD: examples
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache # without it spring cannot find gems
      WEB_CONCURRENCY: 1
    links:
      - db
#      - redis
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/untitled-tournaments
      - cache-volume:/bundle_cache

volumes:
  cache-volume:
