version: '3.7'

services:
  db:
    image: postgres:11.3-alpine
    environment:
      POSTGRES_DB: tournaments-api-development
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  docs:
    image: mattjtodd/raml2html:latest
    working_dir: /docs
    command: -i index.raml -o index.html
    volumes:
      - ./docs:/docs

  schema:
    image: schemacrawler/schemacrawler:latest
    entrypoint: ['/opt/schemacrawler/schemacrawler.sh']
    command: -infolevel=standard -command=schema -sortcolumns -portablenames -outputformat=pdf -outputfile=/docs/db-schema.pdf -server=postgresql -url="jdbc:postgresql://db:5432/tournaments-api-development" -u=postgres -password=postgres
    depends_on:
      - db
    volumes:
      - ./docs:/docs

  web:
    build: .
    working_dir: /tournaments-api
    entrypoint: ["bash", "-c"]
    command: ["rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache # without it spring cannot find gems
      WEB_CONCURRENCY: 1
    depends_on:
      - db
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/tournaments-api
      - cache-volume:/bundle_cache

volumes:
  cache-volume:
