version: '3.3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: untitled-tournaments-development
    ports:
      - '5432:5432'

#  redis:
#    image: redis:latest
#    ports:
#      - '6379:6379'

  web:
    build: .
    working_dir: /untitled-tournaments
    command: ./docker-start.sh
    environment:
      BUNDLE_PATH: /bundle_cache
      WEB_CONCURRENCY: 1
    links:
      - db
#      - redis
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/untitled-tournaments
      - cache-volume:/bundle_cache

volumes:
  cache-volume:
