version: '3.8'

services:
  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  docs:
    image: mattjtodd/raml2html:7.5.0
    working_dir: /docs
    command: -i index.raml -o index.html
    volumes:
      - ./docs:/docs

  schema:
    image: schemacrawler/schemacrawler:v16.8.1
    entrypoint: ['/opt/schemacrawler/schemacrawler.sh']
    command: --info-level=standard --command=schema --sort-columns --portable-names --output-format=pdf --output-file=/docs/db-schema.pdf --url="jdbc:postgresql://db:5432/tournaments-api-development" --user=postgres --password=postgres
    depends_on:
      - db
    volumes:
      - ./docs:/docs

  web:
    build: .
    working_dir: /tournaments-api
    entrypoint: ["sh", "-c"]
    command: ["rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"]
    environment:
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache # without it spring cannot find gems
    env_file:
      - .env.example
    depends_on:
      - db
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    volumes:
      - .:/tournaments-api
      - cache-volume:/bundle_cache

volumes:
  cache-volume:
