default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DATABASE_POOL', 5) %>

development:
  <<: *default
  database: tournaments-api-development
  username: postgres
  password: postgres
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>

test:
  <<: *default
  database: tournaments-api-test
  username: postgres
  password: postgres
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>

#production:
#  <<: *default
#  url: <%#= ENV['DATABASE_URL'] %>
