displayName: Competitor
securedBy: [oauth]
is: [authenticable, authorizable]
post:
  queryParameters:
    tournament_id:
      description: The id of the tournament
      type: uuid
  responses:
    201:
      body:
        type: Competitor
delete:
  queryParameters:
    tournament_id:
      description: The id of the tournament
      type: uuid
  responses:
    204:

/{id}/confirm:
  uriParameters:
    id:
      description: The id of the competitor
      type: uuid
  post:
    securedBy: [oauth]
    is: [authenticable, authorizable]
    responses:
      200:
        body:
          type: Competitor
