displayName: Competitor
securedBy: [oauth]
is: [authenticable, authorizable, findable]
post:
  description: Enlist in a tournament. User can enlist only in tournaments that didn't start.
  queryParameters:
    tournament_id:
      description: The id of the tournament
      type: uuid
  body:
    properties:
      competitor: CompetitorParams
  responses:
    201:
      body:
        properties:
          competitor: Competitor
delete:
  description: Resign from a tournament. User can resign only from tournaments that didn't start.
  queryParameters:
    tournament_id:
      description: The id of the tournament
      type: uuid
  responses:
    204:

/add:
  post:
    description: Create a competitor for user without an account. User can create competitors only in tournaments he created.
    securedBy: [oauth]
    is: [authenticable, authorizable, findable]
    queryParameters:
      tournament_id:
        description: The id of the tournament
        type: uuid
    body:
      properties:
        competitor: CompetitorParams
    responses:
      201:
        body:
          properties:
            competitor: Competitor
