displayName: Competitors
/{id}/remove:
  uriParameters:
    id:
      description: The id of the competitor
      type: uuid
  delete:
    description: Remove competitor from a tournament. User can remove only competitors he created.
    securedBy: [oauth]
    is: [authenticable, authorizable, findable]
    responses:
      204:

/{id}/confirm:
  uriParameters:
    id:
      description: The id of the competitor
      type: uuid
  post:
    description: Confirm user participation in a tournament. User can confirm competitors only in tournaments he created.
    securedBy: [oauth]
    is: [authenticable, authorizable, findable]
    responses:
      200:
        body:
          properties:
            competitor: Competitor

/{id}/reject:
  uriParameters:
    id:
      description: The id of the competitor
      type: uuid
  post:
    description: Reject user participation in a tournament. User can reject competitors only in tournaments he created.
    securedBy: [oauth]
    is: [authenticable, authorizable, findable]
    responses:
      200:
        body:
          properties:
            competitor: Competitor
