displayName: Authentication
/token:
  post:
    queryParameters:
      email: string
      password: string
      grant_type:
        enum: [client_credentials]
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "access_token": "0ddb922452c983a70566e30dce16e2017db335103e35d783874c448862a78168",
                "token_type": "bearer",
                "expires_in": 7200,
                "refresh_token": "f2188c4165d912524e04c6496d10f06803cc08ed50271a0b0a73061e3ac1c06c",
                "scope": "public"
              }
      401:
        body:
          application/json:
            example: |
              {
                "error": "invalid_grant",
                "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."
              }

  /info:
    get:
      securedBy: [oauth]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "resource_owner_id":1,
                  "scopes":[],
                  "expires_in_seconds":7178,
                  "application":{"uid":null},
                  "created_at":1440460991
                }
        401:
          body:
            application/json:
              example: |
                {
                  "error": "invalid_request",
                  "error_description": "The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed."
                }

/revoke:
  post:
    securedBy: [oauth]
    responses:
      200:
