displayName: Players
post:
  securedBy: [oauth]
  queryParameters:
    round_id:
      description: The id of the round
      type: uuid
  responses:
    201:
      body:
        type: Player[]
    401:
    403:
      body:
        type: Error
/{id}:
  uriParameters:
    id:
      description: The id of the player
      type: uuid
  put:
    securedBy: [oauth]
    responses:
      200:
        body:
          type: Player
      401:
      403:
        body:
          type: Error
      422:
        body:
          type: ValidationErrors
