displayName: Players
post:
  description: Assign players to tables in a tournament round. For the first round assignment is random. If consecutive rounds have the same competitors limit and tables count, algorithm tries to pair up competitors who haven't met yet. Otherwise it's based on score. User can assign players only in tournaments he created.
  securedBy: [oauth]
  is: [authenticable, authorizable]
  queryParameters:
    round_id:
      description: The id of the round
      type: uuid
  responses:
    201:
      body:
        properties:
          players: Player[]

/{id}:
  uriParameters:
    id:
      description: The id of the player
      type: uuid
  patch:
    description: Update player with the round results.
    securedBy: [oauth]
    is: [authenticable, authorizable, findable, validatable]
    body:
      properties:
        player: PlayerParams
    responses:
      200:
        body:
          properties:
            player: Player
