displayName: Players
post:
  securedBy: [oauth]
  is: [authenticable, authorizable]
  queryParameters:
    round_id:
      description: The id of the round
      type: uuid
  responses:
    201:
      body:
        type: Player[]

/{id}:
  uriParameters:
    id:
      description: The id of the player
      type: uuid
  patch:
    securedBy: [oauth]
    is: [authenticable, authorizable, validatable]
    responses:
      200:
        body:
          type: Player
