displayName: Rounds
post:
  description: Create a new tournament round. User can create rounds only in tournaments he created and didn't end.
  securedBy: [oauth]
  is: [authenticable, authorizable, findable]
  body:
    properties:
      round: RoundParams
  queryParameters:
    tournament_id:
      description: The id of the tournament
      type: uuid
  responses:
    201:
      body:
        properties:
          round: Round

/{id}:
  securedBy: [oauth]
  is: [authenticable, authorizable, findable]
  uriParameters:
    id:
      description: The id of the round
      type: uuid
  patch:
    description: Update tournament round. User can update rounds only in tournaments he created and didn't end.
    is: [validatable]
    body:
      properties:
        round: RoundParams
    responses:
      200:
        body:
          properties:
            round: Round
  delete:
    description: Remove tournament round. User can remove rounds only in tournaments he created and didn't end.
    responses:
      204:
