post:
  securedBy: [oauth]
  queryParameters:
    tournament_id:
      description: The id of the tournament
      type: uuid
  responses:
    201:
      body:
        type: Round
    401:
    403:
      body:
        type: Error
/{id}:
  securedBy: [oauth]
  uriParameters:
    id:
      description: The id of the round
      type: uuid
  put:
    responses:
      200:
        body:
          type: Round
      401:
      403:
        body:
          type: Error
      422:
        body:
          type: ValidationErrors
  delete:
    responses:
      204:
      401:
      403:
        body:
          type: Error
