displayName: Rounds
post:
  securedBy: [oauth]
  is: [authenticable, authorizable]
  queryParameters:
    tournament_id:
      description: The id of the tournament
      type: uuid
  responses:
    201:
      body:
        type: Round

/{id}:
  securedBy: [oauth]
  is: [authenticable, authorizable]
  uriParameters:
    id:
      description: The id of the round
      type: uuid
  patch:
    is: [validatable]
    responses:
      200:
        body:
          type: Round
  delete:
    responses:
      204:
