get:
  securedBy: [null, oauth]
  queryParameters:
    page:
      description: Specify the page that you want to retrieve
      required: false
      type: integer
      default: 1
  responses:
    200:
      body:
        type: Tournament[]
post:
  securedBy: [oauth]
  responses:
    201:
      body:
        type: Tournament
    401:
    422:
      body:
        type: ValidationErrors
/{id}:
  uriParameters:
    id:
      description: The id of the tournament
      type: uuid
  get:
    responses:
      200:
      body:
        type: Tournament
  put:
    securedBy: [oauth]
    responses:
      200:
        body:
          type: Tournament
      401:
      403:
        body:
          type: Error
      422:
        body:
          type: ValidationErrors
  delete:
    securedBy: [oauth]
    responses:
      204:
      401:
      403:
        body:
          type: Error
  /start:
    post:
      securedBy: [oauth]
      responses:
        200:
          body:
            type: Tournament
        401:
        403:
          body:
            type: Error
  /end:
    post:
      securedBy: [oauth]
      responses:
        200:
          body:
            type: Tournament
        401:
        403:
          body:
            type: Error
