displayName: User
securedBy: [oauth]
get:
  responses:
    200:
      body:
        type: User
    401:
patch:
  responses:
    200:
      body:
        type: User
    401:
    422:
      body:
        type: ValidationErrors
