Error:
  type: object
  properties:
    error:
      description: Error code, e.g. "forbidden".
      type: string
    error_description:
      description: Human-readable error message.
      type: string

ValidationError:
  type: object
  properties:
    error:
      description: Error code, for validation error it is always "invalid_params".
      type: string
    fields:
      description: A hash containing all errors. Hash keys are field names, values are error messages (arrays of string).
      type: hash
