TournamentFilters:
  type: object
  properties:
    starts_at_after:
      description: Specify datetime after which tournaments you want to retrieve should start.
      required: false
      type: datetime
    with_name:
      description: Specify tournament name you want to search for (case insensitive).
      required: false
      type: string
