TournamentFilters:
  type: object
  properties:
    starts_at_after:
      description: Specify datetime after which tournaments you want to retrieve should start.
      required: false
      type: datetime
