Competitor:
  type: object
  properties:
    created_at: datetime
    id: string
    name: string
    status:
      enum: ["enlisted", "confirmed"]
    user_id: uuid

Player:
  type: object
  properties:
    competitor_id: uuid
    id: string
    result_values: number[]
    table_number: integer

Result:
  type: object
  properties:
    competitor_id: uuid
    total: number[]

Round:
  type: object
  properties: &round-properties
    competitors_limit: integer
    created_at: datetime
    id: string
    tables_count: integer

RoundWithRelations:
  displayName: Round
  type: object
  properties:
    <<: *round-properties
    players: Player[]

Tournament:
  type: object
  properties: &tournament-properties
    competitors_limit: integer
    description:
      type: string
      required: false
    id: string
    name: string
    organiser_id: uuid
    result_names: string[]
    starts_at: datetime
    status:
      enum: ["created", "in_progress", "ended"]

TournamentWithRelations:
  displayName: Tournament
  type: object
  properties:
    <<: *tournament-properties
    competitors: Competitor[]
    rounds: RoundWithRelations[]

User:
  type: object
  properties:
    email: string
    id: string
