CompetitorParams:
  type: object
  properties:
    name:
      description: Name under which user wants to participate in a tournament. Must be unique within that tournament.
      type: string

PlayerParams:
  type: object
  properties:
    result_values: integer[]

RoundParams:
  type: object
  properties:
    competitors_limit: integer
    tables_count: integer

TournamentParams:
  type: object
  properties:
    competitors_limit: integer
    description: string
    name: string
    starts_at: datetime
    result_names: string[]

SignUpParams:
  type: object
  properties:
    email: string
    password: string
    password_confirmation: string

UserParams:
  type: object
  properties:
    email:
      type: string
      required: false
    password:
      type: string
      required: false
    password_confirmation:
      type: string
      required: false
