#%RAML 1.0
---
title: Untitled Tournaments
baseUri: http://0.0.0.0:3000

securitySchemes: !include security_schemes.raml
types:  !include types.raml

/oauth: !include endpoints/oauth.raml
/users: !include endpoints/users.raml
/user: !include endpoints/user.raml
/tournaments: !include endpoints/tournaments.raml
/competitor: !include endpoints/competitor.raml
/rounds: !include endpoints/rounds.raml
/players: !include endpoints/players.raml
