#%RAML 1.0
---
title: Untitled Tournaments
description: Back-end for tournament management application.

baseUri: http://0.0.0.0:3000
mediaType: application/json
securitySchemes: !include security_schemes.raml
traits: !include traits.raml
types:  !include types.raml

/users: !include endpoints/users.raml
/oauth: !include endpoints/oauth.raml
/user: !include endpoints/user.raml
/tournaments: !include endpoints/tournaments.raml
/competitor: !include endpoints/competitor.raml
/rounds: !include endpoints/rounds.raml
/players: !include endpoints/players.raml
