#%RAML 1.0
---
title: Untitled Tournaments
baseUri: http://0.0.0.0:3000

/oauth: !include oauth.raml
/users: !include users.raml
/user: !include user.raml
/tournaments: !include tournaments.raml
/competitor: !include competitor.raml
/rounds: !include rounds.raml
/players: !include players.raml
