/token:
  post:
    responses:
      200:
        body:
          application/json:
      401:
        body:
          application/json:
  /info:
    get:
      responses:
        200:
          body:
            application/json:
        401:
          body:
            application/json:
/revoke:
  post:
    responses:
      200:
