oauth:
  type: OAuth 2.0
  describedBy:
    headers:
      Authorization:
        type: string
        example: Bearer 123def789jkl
  settings:
    accessTokenUri: http://0.0.0.0:3000/oauth/token
    authorizationGrants: ["password"]
