authenticable:
  responses:
    401:
      description: Returned when request was not authenticated properly.

authorizable:
  responses:
    403:
      description: Returned when action is not allowed, e.g. required conditions are not met.
      body:
        type: Error

paginated:
  queryParameters:
    page:
      description: Specify the page that you want to retrieve, 25 results are returned per page.
      required: false
      type: integer
      default: 1

validatable:
  responses:
    422:
      description: Returned when sent parameters are not valid.
      body:
        type: ValidationError
