authenticable:
  usage: Apply this to any method that requires authentication.
  responses:
    401:
      description: Returned when request was not authenticated properly.

authorizable:
  usage: Apply this to any method that requires some conditions to be met for execution.
  responses:
    403:
      description: Returned when action is not allowed, e.g. required conditions are not met.
      body:
        type: Error

paginated:
  usage: Apply this to any method that returns paginated results.
  queryParameters:
    page:
      description: Specify the page that you want to retrieve, 25 results are returned per page.
      required: false
      type: integer
      default: 1

validatable:
  usage: Apply this to any method that validates incoming parameters.
  responses:
    422:
      description: Returned when sent parameters are not valid.
      body:
        type: ValidationError
